- file: 01hokkai_rome.zip
  name: 北海道
- file: 02aomori_rome.zip
  name: 青森県
- file: 03iwate_rome.zip
  name: 岩手県
- file: 04miyagi_rome.zip
  name: 宮城県
- file: 05akita_rome.zip
  name: 秋田県
- file: 06yamaga_rome.zip
  name: 山形県
- file: 07fukush_rome.zip
  name: 福島県
- file: 08ibarak_rome.zip
  name: 茨城県
- file: 09tochig_rome.zip
  name: 栃木県
- file: 10gumma_rome.zip
  name: 群馬県
- file: 11saitam_rome.zip
  name: 埼玉県
- file: 12chiba_rome.zip
  name: 千葉県
- file: 13tokyo_rome.zip
  name: 東京都
- file: 14kanaga_rome.zip
  name: 神奈川県
- file: 15niigat_rome.zip
  name: 新潟県
- file: 16toyama_rome.zip
  name: 富山県
- file: 17ishika_rome.zip
  name: 石川県
- file: 18fukui_rome.zip
  name: 福井県
- file: 19yamana_rome.zip
  name: 山梨県
- file: 20nagano_rome.zip
  name: 長野県
- file: 21gifu_rome.zip
  name: 岐阜県
- file: 22shizuo_rome.zip
  name: 静岡県
- file: 23aichi_rome.zip
  name: 愛知県
- file: 24mie_rome.zip
  name: 三重県
- file: 25shiga_rome.zip
  name: 滋賀県
- file: 26kyouto_rome.zip
  name: 京都府
- file: 27osaka_rome.zip
  name: 大阪府
- file: 28hyogo_rome.zip
  name: 兵庫県
- file: 29nara_rome.zip
  name: 奈良県
- file: 30wakaya_rome.zip
  name: 和歌山県
- file: 31tottor_rome.zip
  name: 鳥取県
- file: 32shiman_rome.zip
  name: 島根県
- file: 33okayam_rome.zip
  name: 岡山県
- file: 34hirosh_rome.zip
  name: 広島県
- file: 35yamagu_rome.zip
  name: 山口県
- file: 36tokush_rome.zip
  name: 徳島県
- file: 37kagawa_rome.zip
  name: 香川県
- file: 38ehime_rome.zip
  name: 愛媛県
- file: 39kochi_rome.zip
  name: 高知県
- file: 40fukuok_rome.zip
  name: 福岡県
- file: 41saga_rome.zip
  name: 佐賀県
- file: 42nagasa_rome.zip
  name: 長崎県
- file: 43kumamo_rome.zip
  name: 熊本県
- file: 44oita_rome.zip
  name: 大分県
- file: 45miyaza_rome.zip
  name: 宮崎県
- file: 46kagosh_rome.zip
  name: 鹿児島県
- file: 47okinaw_rome.zip
  name: 沖縄県
