- file: 01hokkai.zip
  name: 北海道
- file: 02aomori.zip
  name: 青森県
- file: 03iwate.zip
  name: 岩手県
- file: 04miyagi.zip
  name: 宮城県
- file: 05akita.zip
  name: 秋田県
- file: 06yamaga.zip
  name: 山形県
- file: 07fukush.zip
  name: 福島県
- file: 08ibarak.zip
  name: 茨城県
- file: 09tochig.zip
  name: 栃木県
- file: 10gumma.zip
  name: 群馬県
- file: 11saitam.zip
  name: 埼玉県
- file: 12chiba.zip
  name: 千葉県
- file: 13tokyo.zip
  name: 東京都
- file: 14kanaga.zip
  name: 神奈川県
- file: 15niigat.zip
  name: 新潟県
- file: 16toyama.zip
  name: 富山県
- file: 17ishika.zip
  name: 石川県
- file: 18fukui.zip
  name: 福井県
- file: 19yamana.zip
  name: 山梨県
- file: 20nagano.zip
  name: 長野県
- file: 21gifu.zip
  name: 岐阜県
- file: 22shizuo.zip
  name: 静岡県
- file: 23aichi.zip
  name: 愛知県
- file: 24mie.zip
  name: 三重県
- file: 25shiga.zip
  name: 滋賀県
- file: 26kyouto.zip
  name: 京都府
- file: 27osaka.zip
  name: 大阪府
- file: 28hyogo.zip
  name: 兵庫県
- file: 29nara.zip
  name: 奈良県
- file: 30wakaya.zip
  name: 和歌山県
- file: 31tottor.zip
  name: 鳥取県
- file: 32shiman.zip
  name: 島根県
- file: 33okayam.zip
  name: 岡山県
- file: 34hirosh.zip
  name: 広島県
- file: 35yamagu.zip
  name: 山口県
- file: 36tokush.zip
  name: 徳島県
- file: 37kagawa.zip
  name: 香川県
- file: 38ehime.zip
  name: 愛媛県
- file: 39kochi.zip
  name: 高知県
- file: 40fukuok.zip
  name: 福岡県
- file: 41saga.zip
  name: 佐賀県
- file: 42nagasa.zip
  name: 長崎県
- file: 43kumamo.zip
  name: 熊本県
- file: 44oita.zip
  name: 大分県
- file: 45miyaza.zip
  name: 宮崎県
- file: 46kagosh.zip
  name: 鹿児島県
- file: 47okinaw.zip
  name: 沖縄県
